// Lista curada de emoji unicode comuns (não é o catálogo CLDR completo - de propósito,
// pra não puxar dependência nova só pro picker). Cada entrada tem `keywords` em
// português/inglês pra busca simples (EmojiPicker.jsx filtra por substring em
// name+keywords). Categorias inspiradas no agrupamento clássico (Discord/Slack).
export const EMOJI_CATEGORIES = [
  {
    label: "Carinhas",
    emojis: [
      { char: "😀", name: "rindo", keywords: "feliz sorrindo grin happy" },
      { char: "😄", name: "sorrindo", keywords: "feliz olhos happy smile" },
      { char: "😁", name: "sorriso aberto", keywords: "feliz grin happy" },
      { char: "😂", name: "chorando de rir", keywords: "lol kkk lágrima joy" },
      { char: "🤣", name: "rolando de rir", keywords: "lol kkk rofl" },
      { char: "🙂", name: "sorriso leve", keywords: "smile ok" },
      { char: "🙃", name: "de cabeça pra baixo", keywords: "upside down irônico" },
      { char: "😉", name: "piscando", keywords: "wink flerte" },
      { char: "😊", name: "sorrindo tímido", keywords: "blush feliz" },
      { char: "😍", name: "apaixonado", keywords: "amor love coração olhos" },
      { char: "😘", name: "beijo", keywords: "kiss love" },
      { char: "😜", name: "língua pra fora piscando", keywords: "brincalhão wink" },
      { char: "🤔", name: "pensando", keywords: "thinking dúvida hmm" },
      { char: "😎", name: "óculos escuros", keywords: "cool descolado" },
      { char: "🥳", name: "festa", keywords: "party comemoração parabéns" },
      { char: "😴", name: "dormindo", keywords: "sleep sono zzz" },
      { char: "😭", name: "chorando muito", keywords: "sad triste cry" },
      { char: "😢", name: "chorando", keywords: "sad triste tear" },
      { char: "😡", name: "bravo", keywords: "raiva angry mad" },
      { char: "😱", name: "gritando de susto", keywords: "medo scream shock" },
      { char: "😳", name: "envergonhado", keywords: "blush flushed" },
      { char: "🙄", name: "revirando os olhos", keywords: "eyeroll tédio" },
      { char: "😏", name: "sorriso maroto", keywords: "smirk sarcasmo" },
      { char: "🥺", name: "olhinho de pidão", keywords: "pleading suplicando" },
      { char: "😬", name: "sem graça", keywords: "grimace desconfortável" },
      { char: "🤯", name: "cabeça explodindo", keywords: "mind blown chocado" },
      { char: "🤗", name: "abraço", keywords: "hug carinho" },
      { char: "😇", name: "anjinho", keywords: "angel santo" },
      { char: "🤤", name: "babando", keywords: "drool desejo comida" },
    ],
  },
  {
    label: "Gestos e pessoas",
    emojis: [
      { char: "👍", name: "joinha", keywords: "like positivo ok thumbs up" },
      { char: "👎", name: "joinha negativo", keywords: "dislike thumbs down" },
      { char: "👏", name: "palmas", keywords: "clap aplauso parabéns" },
      { char: "🙌", name: "mãos pra cima", keywords: "celebração praise" },
      { char: "🙏", name: "mãos juntas", keywords: "obrigado please pray" },
      { char: "👋", name: "aceno", keywords: "oi tchau wave hello bye" },
      { char: "💪", name: "braço forte", keywords: "força muscle strong" },
      { char: "✌️", name: "paz e amor", keywords: "peace vitória" },
      { char: "🤝", name: "aperto de mão", keywords: "handshake acordo" },
      { char: "👀", name: "olhos", keywords: "eyes olhando reparando" },
      { char: "🤷", name: "dando de ombros", keywords: "shrug sei lá não sei" },
      { char: "💀", name: "caveira", keywords: "morto kkk sem palavras skull" },
      { char: "🔥", name: "fogo", keywords: "fire top demais" },
      { char: "💯", name: "cem pontos", keywords: "100 perfeito top" },
      { char: "❤️", name: "coração vermelho", keywords: "amor love" },
      { char: "💙", name: "coração azul", keywords: "amor love blue" },
      { char: "💚", name: "coração verde", keywords: "amor love green" },
      { char: "💛", name: "coração amarelo", keywords: "amor love yellow" },
      { char: "🧡", name: "coração laranja", keywords: "amor love orange" },
      { char: "💜", name: "coração roxo", keywords: "amor love purple" },
      { char: "🖤", name: "coração preto", keywords: "amor love black" },
      { char: "💔", name: "coração partido", keywords: "heartbroken triste" },
    ],
  },
  {
    label: "Animais e natureza",
    emojis: [
      { char: "🐶", name: "cachorro", keywords: "dog pet" },
      { char: "🐱", name: "gato", keywords: "cat pet" },
      { char: "🦊", name: "raposa", keywords: "fox" },
      { char: "🐻", name: "urso", keywords: "bear" },
      { char: "🐼", name: "panda", keywords: "panda" },
      { char: "🐸", name: "sapo", keywords: "frog" },
      { char: "🐵", name: "macaco", keywords: "monkey" },
      { char: "🦄", name: "unicórnio", keywords: "unicorn" },
      { char: "🐔", name: "galinha", keywords: "chicken" },
      { char: "🐢", name: "tartaruga", keywords: "turtle devagar" },
      { char: "🐙", name: "polvo", keywords: "octopus" },
      { char: "🦋", name: "borboleta", keywords: "butterfly" },
      { char: "🌸", name: "flor de cerejeira", keywords: "flower spring" },
      { char: "🌵", name: "cacto", keywords: "cactus" },
      { char: "🌈", name: "arco-íris", keywords: "rainbow" },
      { char: "☀️", name: "sol", keywords: "sun calor dia" },
      { char: "🌙", name: "lua", keywords: "moon noite" },
      { char: "⭐", name: "estrela", keywords: "star" },
      { char: "⚡", name: "raio", keywords: "lightning energia rápido" },
      { char: "❄️", name: "floco de neve", keywords: "snow frio" },
    ],
  },
  {
    label: "Comida",
    emojis: [
      { char: "🍕", name: "pizza", keywords: "pizza comida" },
      { char: "🍔", name: "hambúrguer", keywords: "burger comida" },
      { char: "🍟", name: "batata frita", keywords: "fries comida" },
      { char: "🌭", name: "cachorro-quente", keywords: "hotdog" },
      { char: "🍿", name: "pipoca", keywords: "popcorn cinema" },
      { char: "🍩", name: "rosquinha", keywords: "donut doce" },
      { char: "🍰", name: "bolo", keywords: "cake aniversário" },
      { char: "🍫", name: "chocolate", keywords: "chocolate doce" },
      { char: "🍦", name: "sorvete", keywords: "icecream sobremesa" },
      { char: "🍺", name: "cerveja", keywords: "beer bebida" },
      { char: "🍷", name: "vinho", keywords: "wine bebida" },
      { char: "☕", name: "café", keywords: "coffee bebida" },
      { char: "🍎", name: "maçã", keywords: "apple fruta" },
      { char: "🍌", name: "banana", keywords: "banana fruta" },
      { char: "🍇", name: "uva", keywords: "grape fruta" },
    ],
  },
  {
    label: "Objetos e símbolos",
    emojis: [
      { char: "🎉", name: "confete", keywords: "party comemoração parabéns" },
      { char: "🎂", name: "bolo de aniversário", keywords: "birthday cake" },
      { char: "🎁", name: "presente", keywords: "gift presente" },
      { char: "🎮", name: "controle de video game", keywords: "game jogo" },
      { char: "🎧", name: "fone de ouvido", keywords: "headphones música audio" },
      { char: "🎵", name: "nota musical", keywords: "music música" },
      { char: "💻", name: "notebook", keywords: "computer laptop trabalho" },
      { char: "📱", name: "celular", keywords: "phone smartphone" },
      { char: "📷", name: "câmera", keywords: "camera foto" },
      { char: "💡", name: "lâmpada", keywords: "idea ideia luz" },
      { char: "🔒", name: "cadeado", keywords: "lock privado seguro" },
      { char: "🔔", name: "sino", keywords: "bell notificação" },
      { char: "✅", name: "check verde", keywords: "ok feito done" },
      { char: "❌", name: "x vermelho", keywords: "erro cancelar wrong" },
      { char: "⚠️", name: "aviso", keywords: "warning atenção alerta" },
      { char: "❓", name: "interrogação", keywords: "question dúvida" },
      { char: "❗", name: "exclamação", keywords: "exclamation atenção" },
      { char: "💤", name: "dormindo zzz", keywords: "sleep sono ausente" },
      { char: "🚀", name: "foguete", keywords: "rocket lançamento rápido" },
      { char: "🎯", name: "alvo", keywords: "target foco objetivo" },
    ],
  },
];
